"""
AnalyticalBlackLight
Made by perpetualCreations

Uses pytrends as a black light on student cheating during virtual testing.
This serves as a tool to increase the number of keywords that can be analyzed at the same time.
Additionally can generate a plot of search interest, or return as a pandas dataframe for further data science processing.

List of keywords must be a multiple of 5.
TODO implement argparse
"""

from pytrends.request import TrendReq
from random import randint
import pandas, configparser
import argparse

# blank target parameter objects
target_date_1 = None
target_date_2 = None
target_country = None
target_state = None
target_county = None

pytrend = TrendReq() # object for requesting trends payloads.

collection_list = [] # dataframes generated by collect() are appended to this list.
collect_cycle = 0 # collection cycles elapsed.

def keywords_read():
    """
    Reads keywords.
    :return: list of keywords.
    """
    with open("keywords.txt") as keywords:
        return keywords.read().splitlines()
    pass
pass

def config_read():
    """
    Reads targets.cfg.
    :return: none.
    """
    global target_date_1, target_date_2, target_country, target_state, target_county
    targets_parser = configparser.ConfigParser()
    targets_parser.read("targets.cfg")
    target_date_1 = targets_parser["TIME"]["date_1"]
    target_date_2 = targets_parser["TIME"]["date_2"]
    target_country = targets_parser["LOCATION"]["country"]
    target_state = targets_parser["LOCATION"]["state"]
    target_county = targets_parser["LOCATION"]["county"]
pass

print("Targets: \nFirst Date: " + target_date_1 + "\nSecond Date: " + target_date_2 + "\nCountry: " + target_country +
      "\nState: " + target_state + "\nCounty Code: " + target_county + "\n")
print("Loaded keywords: ")
print(keywords_read())

# data requests
while collect_cycle != len(keywords_read()):
    pytrend.build_payload(
        [keywords_read()[collect_cycle], keywords_read()[collect_cycle + 1], keywords_read()[collect_cycle + 2],
         keywords_read()[collect_cycle + 3], keywords_read()[collect_cycle + 4]],
        timeframe=target_date_1 + " " + target_date_2,
        geo=target_country + "-" + target_state + "-" + target_county)
    collection_list.append(pytrend.interest_over_time())
    collect_cycle += 5
pass

# merging dataframes
export_dataframe = pandas.concat(collection_list, axis = 1)

def export():
    """
    Exports data to CSV. TODO file path -> argparse
    :return:
    """
    export_dataframe.to_csv((input("Export Path: ") + str(randint(1, 9999999)) + ".csv"))
pass

def graph():
    """
    Matplotlib graphing from CSV data.
    :return:
    """

pass
